from src.adapters.ollama_llm_adapter import OllamaLLMAdapter
from src.adapters.subprocess_code_executor import SubprocessCodeExecutor
from src.models.execution_result import ExecutionResult
from pathlib import Path




class Charts_Agent:
    def __init__(self, llm, executor, system_prompt: str, max_attempts: int = 3):
        self.system = system_prompt # store the system prompt
        self.messages = [] # this will contain the entire conversation history
        self.llm = llm
        self.executor = executor
        self.max_attempts = max_attempts

        if self.system: # if a system prompt exist, store it as the first message in history
            self.messages.append({'role':'system', 'content':system_prompt})

    def __call__(self, message):
        self.messages.append({'role': 'user', 'content': message})
        result = self.llm.chat(self.messages) 
        self.messages.append({'role': 'assistant', 'content': result})
        return result

    def _format_execution_result(self, result: ExecutionResult) -> str:
        if result.success and result.generated_files:
             return (
            "Execution succeeded.\n"
            f"STDOUT:\n{result.stdout}\n\n"
            f"Generated HTML files:\n"
            + "\n".join(str(path) for path in result.generated_files)
        )

        return (
            "Execution failed.\n"
            f"Timed out: {result.timed_out}\n"
            f"Exit code: {result.exit_code}\n\n"
            f"STDOUT:\n{result.stdout}\n\n"
            f"STDERR:\n{result.stderr}\n"
        )

    def execute_python_code(self, code: str, dataset_path: Path) -> tuple[str, ExecutionResult]:
        """Execute the python generated code"""
        result = self.executor.execute_code(code, dataset_path)
        return self._format_execution_result(result), result
        

    # ReAct LOOP
    def run(self, user_request: str, dataset_path: Path) -> ExecutionResult:
        prompt = self._build_initial_prompt(user_request)
        
        last_result = None

        for attempt in range(1, self.max_attempts + 1):
            print(f"\n--- Agent attempt {attempt}/{self.max_attempts} ---")
            generated_code = self(prompt)
            #print(type(generated_code))
            print(90*"=")
            print("Code generated by llm: \n")
            print(generated_code)
            print(90*"=")
            observation, result = self.execute_python_code(generated_code, dataset_path)
            print(observation)
            
            if result.success and result.generated_files:
                return result
            prompt = self._build_retry_prompt(observation)



    def _build_initial_prompt(self, user_request: str) -> str:
        return f"""
User request:
{user_request}

Generate Python code to satisfy the request.

Important rules:
- Return only executable python code
- Do not use markdown
- Do not explain the code
- The input dataset is available in the working directory as input.csv, input.xlsx or input.json depending on the file extension.
- Use Plotly for visualization.
- Save at least one Plotly chart as an HTML file.
- Use relative paths only.
- Do not access the internet.           
""".strip()


    def _build_retry_prompt(self, observation: str) -> str:
        return f"""
Observation from previous execution:
{observation}
The previous code failed or did not generate a valid HTML plot.
Please generate corrected Python code.
Rules:
- Return only executable Python code
- Do not use markdown
- Do not explain the code
""".strip()









